#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
gems: [jekyll-paginate]
# Config sass build output by sass_dir
# Config sass output is compressed or not
#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: "Blog - Jeffrey Asselin"
description: "Where I write about data, sports, books, and everything else"
keywords: "Data Science"
locale: "en_US"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
url: "https://jassassin68.github.io"
baseurl: "/"
permalink: /:year/:month/:day/:title


# Pagination
## Set per_page to 0 to disable pagination
paginate: 5
paginate_path: "/page:num/"


# Writing
highlighter: 'rouge'
kramdown:
  input:  GFM
  enable_coderay: true
  coderay:
    coderay_line_numbers:  nil

# RSS
#rss:
#  path: "/feed.xml"
#  icon: "rss"


#---------------------------------------------------------------
# Authour infromation setting
#---------------------------------------------------------------

# Author
author:
  name: "Jeffrey Asselin"
  avatar: "https://media.licdn.com/dms/image/C5603AQEUpxrFeplZWw/profile-displayphoto-shrink_200_200/0?e=1565222400&v=beta&t=1WGyra1H5WJFEkOsqVShnnlIVM7A4rXtoouMrtnbJz4"
  motto: "keep it simple"

# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
#    - name: "weibo"
#      url: "http://www.weibo.com/usename/"
#      icon: "weibo"
    - name: "github"
      url: "https://github.com/jassassin68"
      icon: "github"
#    - name: "facebook"
#      url: "https://www.facebook.com/usename"
#      icon: "facebook"




#---------------------------------------------------------------
# Site comment setting
#---------------------------------------------------------------

comment:
  enable: false

# duoshuo
duoshuo:
  enable: false
  short_name: "your duoshuo short_name"

# disqus
disqus:
  enable: false
  short_name: "your disqus short_name"

#---------------------------------------------------------------
# Site share setting
#---------------------------------------------------------------
duoshuo_share:
    enable: false

#---------------------------------------------------------------
# Site analysis setting
#---------------------------------------------------------------
# Baidu analysis
baidu_analysis:
  enable: false
  token: "your baidu analysis token"

# Google analysis
google_analysus:
  enable: false
  token: "your google analysis token"
